In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import os

EVD

In [28]:
#step1-创建数据（n=5（样本数），d=3（特征/维度/变量））
X1 = [1,2,34]
X2 = [4,8,60]
X3 = [7,20,99]
X4 = [10,11,52]
X5 = [13,24,55]

X = np.vstack((X1,X2,X3,X4,X5))

In [29]:
#step2-零均值化处理
print("X[:,0].mean()=",X[:,0].mean())
X[:,0] = X[:,0] - X[:,0].mean()

print("X[:,1].mean()=",X[:,1].mean())
X[:,1] = X[:,1] - X[:,1].mean()

print("X[:,2].mean()=",X[:,2].mean())
X[:,2] = X[:,2] - X[:,2].mean()

X[:,0].mean()= 7.0
X[:,1].mean()= 13.0
X[:,2].mean()= 60.0


In [30]:
X

array([[ -6, -11, -26],
       [ -3,  -5,   0],
       [  0,   7,  39],
       [  3,  -2,  -8],
       [  6,  11,  -5]])

In [43]:
#step3-计算协方差矩阵

C = X.T.dot(X)/(X.shape[0]-1)

#another way: np.cov(X,rowvar=False)
#注意np.cov()默认每行为一个特征/维度/变量（variable），每列为一个样本（observations）

print("C = ",C)

C =  [[ 22.5   35.25  25.5 ]
 [ 35.25  80.   130.  ]
 [ 25.5  130.   571.5 ]]


In [48]:
#step4-计算协方差矩阵的特征值与特征向量
evalue, evector = np.linalg.eig(C)

print(evalue)
print("#"*40)
print(evector)

[605.66561586   3.0344702   65.29991394]
########################################
[[-0.05704527 -0.84594283 -0.53021369]
 [-0.24328528  0.52684778 -0.81439774]
 [-0.96827584 -0.08253565  0.23585961]]


In [67]:
#step5-检验

lambda_df = np.zeros((3,3))
lambda_df[0,0]=evalue[0]
lambda_df[1,1]=evalue[1]
lambda_df[2,2]=evalue[2]

q1 = evector[0]
q2 = evector[1]
q3 = evector[2]
Q = np.array([q1,q2,q3])

print("检验结果：",Q.dot(lambda_df).dot(Q.T))
print("#"*40)
print("正确答案：",C)

检验结果： [[ 22.5   35.25  25.5 ]
 [ 35.25  80.   130.  ]
 [ 25.5  130.   571.5 ]]
########################################
正确答案： [[ 22.5   35.25  25.5 ]
 [ 35.25  80.   130.  ]
 [ 25.5  130.   571.5 ]]


In [76]:
#step6-计算零均值化后的数据在每个特征向量上投影后的值的方差，并作出选择判断
var1 = np.var(X.dot(evector[0]))
print("var1 = ",var1)
var2 = np.var(X.dot(evector[1]))
print("var2 = ",var2)
var3 = np.var(X.dot(evector[2]))
print("var3 = ",var3)
print("选择信息量最大（方差最大）的var1与var2")

var1 =  271.63935086642533
var2 =  233.67425582091124
var3 =  33.88639331266353
选择信息量最大（方差最大）的var1与var2


In [79]:
#step7-将3维数据压缩到2维（5x3 * 3x2  →  5x2）
X.dot(Q.T[:,:2])

array([[ 23.43319877,  16.83872737],
       [  4.40084998,  -1.90438309],
       [-26.5999338 , -28.07357751],
       [  5.76245939,   4.73163055],
       [ -6.99657434,   8.40760268]])

SVD

In [16]:
A = [[0,0,0,2,2],
     [0,0,0,3,3],
     [0,0,0,1,1],
     [1,1,1,0,0],
     [2,2,2,0,0],
     [5,5,5,0,0],
     [1,1,1,0,0]]

A = np.array(A)
print("A.shape : ",A.shape)

A.shape :  (7, 5)


In [11]:
U,sigma,Vt = np.linalg.svd(A)

In [26]:
sigma

array([9.64365076e+00, 5.29150262e+00, 7.40623935e-16, 4.05103551e-16,
       2.21838243e-32])

In [27]:
U

array([[-2.22044605e-16,  5.34522484e-01,  8.41650989e-01,
         5.59998398e-02, -5.26625636e-02,  2.77555756e-17,
         1.38777878e-17],
       [ 0.00000000e+00,  8.01783726e-01, -4.76944344e-01,
        -2.09235996e-01,  2.93065263e-01, -4.01696905e-17,
        -2.77555756e-17],
       [ 0.00000000e+00,  2.67261242e-01, -2.52468946e-01,
         5.15708308e-01, -7.73870662e-01,  1.54769615e-16,
         8.59497045e-18],
       [-1.79605302e-01,  0.00000000e+00,  7.39748546e-03,
        -3.03901436e-01, -2.04933639e-01,  8.94308074e-01,
        -1.83156768e-01],
       [-3.59210604e-01,  0.00000000e+00,  1.47949709e-02,
        -6.07802873e-01, -4.09867278e-01, -4.47451355e-01,
        -3.64856984e-01],
       [-8.98026510e-01,  0.00000000e+00, -8.87698255e-03,
         3.64681724e-01,  2.45920367e-01, -1.07974157e-16,
        -1.66854263e-17],
       [-1.79605302e-01,  0.00000000e+00,  7.39748546e-03,
        -3.03901436e-01, -2.04933639e-01,  5.94635264e-04,
         9.1287073

In [28]:
Vt

array([[-5.77350269e-01, -5.77350269e-01, -5.77350269e-01,
         0.00000000e+00,  0.00000000e+00],
       [-2.46566547e-16,  1.23283273e-16,  1.23283273e-16,
         7.07106781e-01,  7.07106781e-01],
       [-7.83779232e-01,  5.90050124e-01,  1.93729108e-01,
        -2.77555756e-16, -2.22044605e-16],
       [-2.28816045e-01, -5.64364703e-01,  7.93180748e-01,
         2.22044605e-16, -1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -7.07106781e-01,  7.07106781e-01]])

In [29]:
Vt[0,:]

array([-0.57735027, -0.57735027, -0.57735027,  0.        ,  0.        ])

In [20]:
#SVD行压缩--U.T*A
U_T_2_7 = U.T[:2,:]


svd_col = U_T_2_7.dot(A)
print("压缩前的行数：",A.shape[0])
print("压缩前的列数：",A.shape[1])
print("#"*40)
print("压缩后的行数：",svd_col.shape[0])
print("压缩后的列数：",svd_col.shape[1])


压缩前的行数： 7
压缩前的列数： 5
########################################
压缩后的行数： 2
压缩后的列数： 5


In [25]:
#SVD列压缩--V.T*A.T
V_T_2_5 = Vt[:2,:]


svd_row = V_T_2_5.dot(A.T).T  #因为压缩的是A.T，结果还需要再转置
print("压缩前的行数：",A.shape[0])
print("压缩前的列数：",A.shape[1])
print("#"*40)
print("压缩后的行数：",svd_row.shape[0])
print("压缩后的列数：",svd_row.shape[1])

压缩前的行数： 7
压缩前的列数： 5
########################################
压缩后的行数： 7
压缩后的列数： 2


In [48]:
#SVD近似-- sigma1*u1*vt1 + sigma2*u2*vt2

svd_apx1 = np.dot(sigma[0]*U[:,0].reshape(-1,1),(Vt[0,:]).reshape(-1,1).T)
svd_apx2 = np.dot(sigma[1]*U[:,1].reshape(-1,1),(Vt[1,:]).reshape(-1,1).T)

svd_apx = svd_apx1 + svd_apx2

In [51]:
svd_apx

array([[ 5.38896529e-16,  1.58498979e-15,  1.58498979e-15,
         2.00000000e+00,  2.00000000e+00],
       [-1.04609326e-15,  5.23046632e-16,  5.23046632e-16,
         3.00000000e+00,  3.00000000e+00],
       [-3.48697754e-16,  1.74348877e-16,  1.74348877e-16,
         1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 2.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 5.00000000e+00,  5.00000000e+00,  5.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00]])