In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import os

In [28]:
#step1-创建数据（n=5（样本数），d=3（特征/维度/变量））
X1 = [1,2,34]
X2 = [4,8,60]
X3 = [7,20,99]
X4 = [10,11,52]
X5 = [13,24,55]

X = np.vstack((X1,X2,X3,X4,X5))

In [29]:
#step2-零均值化处理
print("X[:,0].mean()=",X[:,0].mean())
X[:,0] = X[:,0] - X[:,0].mean()

print("X[:,1].mean()=",X[:,1].mean())
X[:,1] = X[:,1] - X[:,1].mean()

print("X[:,2].mean()=",X[:,2].mean())
X[:,2] = X[:,2] - X[:,2].mean()

X[:,0].mean()= 7.0
X[:,1].mean()= 13.0
X[:,2].mean()= 60.0


In [30]:
X

array([[ -6, -11, -26],
       [ -3,  -5,   0],
       [  0,   7,  39],
       [  3,  -2,  -8],
       [  6,  11,  -5]])

In [43]:
#step3-计算协方差矩阵

C = X.T.dot(X)/(X.shape[0]-1)

#another way: np.cov(X,rowvar=False)
#注意np.cov()默认每行为一个特征/维度/变量（variable），每列为一个样本（observations）

print("C = ",C)

C =  [[ 22.5   35.25  25.5 ]
 [ 35.25  80.   130.  ]
 [ 25.5  130.   571.5 ]]


In [48]:
#step4-计算协方差矩阵的特征值与特征向量
evalue, evector = np.linalg.eig(C)

print(evalue)
print("#"*40)
print(evector)

[605.66561586   3.0344702   65.29991394]
########################################
[[-0.05704527 -0.84594283 -0.53021369]
 [-0.24328528  0.52684778 -0.81439774]
 [-0.96827584 -0.08253565  0.23585961]]


In [67]:
#step5-检验

lambda_df = np.zeros((3,3))
lambda_df[0,0]=evalue[0]
lambda_df[1,1]=evalue[1]
lambda_df[2,2]=evalue[2]

q1 = evector[0]
q2 = evector[1]
q3 = evector[2]
Q = np.array([q1,q2,q3])

print("检验结果：",Q.dot(lambda_df).dot(Q.T))
print("#"*40)
print("正确答案：",C)

检验结果： [[ 22.5   35.25  25.5 ]
 [ 35.25  80.   130.  ]
 [ 25.5  130.   571.5 ]]
########################################
正确答案： [[ 22.5   35.25  25.5 ]
 [ 35.25  80.   130.  ]
 [ 25.5  130.   571.5 ]]


In [76]:
#step6-计算零均值化后的数据在每个特征向量上投影后的值的方差，并作出选择判断
var1 = np.var(X.dot(evector[0]))
print("var1 = ",var1)
var2 = np.var(X.dot(evector[1]))
print("var2 = ",var2)
var3 = np.var(X.dot(evector[2]))
print("var3 = ",var3)
print("选择信息量最大（方差最大）的var1与var2")

var1 =  271.63935086642533
var2 =  233.67425582091124
var3 =  33.88639331266353
选择信息量最大（方差最大）的var1与var2


In [79]:
#step7-将3维数据压缩到2维（5x3 * 3x2  →  5x2）
X.dot(Q.T[:,:2])

array([[ 23.43319877,  16.83872737],
       [  4.40084998,  -1.90438309],
       [-26.5999338 , -28.07357751],
       [  5.76245939,   4.73163055],
       [ -6.99657434,   8.40760268]])